# This is a basic workflow that is manually triggered

name: s3 check 

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
   
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create bucket in S3
      uses: alialrubaye/aws-s3-create-bucket@1.0.1
      with:
        bucket-name: 'ali-test55'
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-2'        
   
